version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stepbystep
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/var/lib/postgresql/data

  stepbystep:
    build: .
    restart: on-failure
    ports:
      - "8002:8000"
    environment:
      PYTHONPATH: "/work"
      SQLALCHEMY_DATABASE_URL: "postgresql+psycopg2://postgres:postgres@postgres/stepbystep"
    volumes:
      - ./logs:/work/logs
    command: ./wait-for-it.sh postgres:5432 -t 120 -- uvicorn --host 0.0.0.0 main:app

volumes:
  db:
  logs: