"""empty message

Revision ID: 023a40d05045
Revises: 4944924a7ba1
Create Date: 2021-04-01 19:20:01.082902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023a40d05045'
down_revision = '4944924a7ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'problems', ['source_id', 'problem_id'])
    op.create_unique_constraint(None, 'solutions', ['source_id', 'bind_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solutions', type_='unique')
    op.drop_constraint(None, 'problems', type_='unique')
    # ### end Alembic commands ###
