"""empty message

Revision ID: 09629fcf2e41
Revises: 0695af62276b
Create Date: 2021-05-19 16:17:12.906815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09629fcf2e41'
down_revision = '0695af62276b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step_problem', type_='foreignkey')
    op.create_foreign_key(None, 'step_problem', 'steps', ['step_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'step_user', type_='foreignkey')
    op.create_foreign_key(None, 'step_user', 'steps', ['step_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step_user', type_='foreignkey')
    op.create_foreign_key(None, 'step_user', 'steps', ['step_id'], ['id'])
    op.drop_constraint(None, 'step_problem', type_='foreignkey')
    op.create_foreign_key(None, 'step_problem', 'steps', ['step_id'], ['id'])
    # ### end Alembic commands ###
