"""empty message

Revision ID: 0e778869ac00
Revises: 4944924a7ba1
Create Date: 2021-04-01 19:24:27.940823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e778869ac00'
down_revision = '4944924a7ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'problems', ['source_id', 'problem_id'])
    op.create_index('solution_bind_user_id_problem_id', 'solutions', ['bind_user_id', 'problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('solution_bind_user_id_problem_id', table_name='solutions')
    op.drop_constraint(None, 'problems', type_='unique')
    # ### end Alembic commands ###
