"""empty message

Revision ID: 4944924a7ba1
Revises: c1cc3d1033d5
Create Date: 2021-03-26 18:38:40.887586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4944924a7ba1'
down_revision = 'c1cc3d1033d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_solutions_submitted_at'), 'solutions', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solutions_submitted_at'), table_name='solutions')
    # ### end Alembic commands ###
