"""empty message

Revision ID: c1cc3d1033d5
Revises: 9465d3880563
Create Date: 2021-03-26 16:00:05.073924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1cc3d1033d5'
down_revision = '9465d3880563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'problems', ['source_id', 'problem_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='unique')
    # ### end Alembic commands ###
