# Generated by Django 3.1.4 on 2020-12-07 13:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sourceuser',
            unique_together={('user', 'source', 'username')},
        ),
    ]
