# Generated by Django 3.1.4 on 2020-12-07 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0002_auto_20201207_1318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sourceuser',
            unique_together={('user', 'source')},
        ),
    ]
